LIMITE_INFERIOR = -512
LIMITE_SUPERIOR = 512

TAMANHO_POPULACAO = 100
NUM_GERACOES = 100
REDUCAO_POR_GERACAO = 0.9

TAXA_CROSSOVER = 0.8
TAXA_MUTACAO = 0.1

FUNCAO: Callable[[int], float] = lambda x: (-(x - 3) ** 2) + 10